// <auto-generated />
using System;
using HappyGymStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyGymStats.Data.Migrations
{
    [DbContext(typeof(HappyGymStatsDbContext))]
    [Migration("20260430145603_StoreTimestampsAsUtcDateTime")]
    partial class StoreTimestampsAsUtcDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("HappyGymStats.Data.Entities.DerivedGymTrainEntity", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClampedToMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyAfterTrain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyBeforeTrain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHappyAtTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegenHappyGained")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegenTicksApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("DerivedGymTrains");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.DerivedHappyEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Delta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HappyAfterEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyBeforeEvent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLogId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SourceLogId");

                    b.ToTable("DerivedHappyEvents");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportCheckpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunOutcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalAppendedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFetchedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ImportCheckpoints");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("LogsAppended")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LogsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.RawUserLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("RawUserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
