// <auto-generated />
using System;
using HappyGymStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappyGymStats.Data.Migrations
{
    [DbContext(typeof(HappyGymStatsDbContext))]
    partial class HappyGymStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HappyGymStats.Data.Entities.AffiliationEventEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceLogEntryId")
                        .HasColumnType("text");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("EncryptedAffiliationId")
                        .HasColumnType("bytea");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionBefore")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("AnonymousId", "SourceLogEntryId");

                    b.HasIndex("AnonymousId", "Scope", "AffiliationId");

                    b.ToTable("AffiliationEvents");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ConsentRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "AnonymousId");

                    b.HasIndex("AnonymousId", "Purpose", "DocumentVersion");

                    b.HasIndex("AnonymousId", "Purpose", "RevokedAtUtc");

                    b.ToTable("ConsentRecords", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.FactionIdMapEntity", b =>
                {
                    b.Property<int>("AffiliationId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactionAnonymousId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("AffiliationId");

                    b.HasIndex("FactionAnonymousId")
                        .IsUnique();

                    b.ToTable("FactionIdMap");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.FactionMembershipEntity", b =>
                {
                    b.Property<Guid>("FactionAnonymousId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberAnonymousId")
                        .HasColumnType("uuid");

                    b.HasKey("FactionAnonymousId", "MemberAnonymousId");

                    b.HasIndex("MemberAnonymousId");

                    b.ToTable("FactionMembership");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.IdentityMapEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedTornPlayerId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakSub")
                        .HasColumnType("text");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea");

                    b.HasKey("AnonymousId");

                    b.HasIndex("KeycloakSub")
                        .IsUnique()
                        .HasFilter("\"KeycloakSub\" IS NOT NULL");

                    b.ToTable("IdentityMap");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("LogsAppended")
                        .HasColumnType("bigint");

                    b.Property<long>("LogsFetched")
                        .HasColumnType("bigint");

                    b.Property<string>("NextUrl")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("AnonymousId", "StartedAtUtc");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.LogTypeEntity", b =>
                {
                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LogTypeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogTypeId");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ModifierProvenanceEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("AnonymousId", "LogEntryId", "Scope");

                    b.HasIndex("AnonymousId", "VerificationStatus");

                    b.ToTable("ModifierProvenance");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.RankedWarHistoryBackfillStateEntity", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("LastFailureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailureCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("LastProcessedWarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextHistoryPageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PagesProcessed")
                        .HasColumnType("bigint");

                    b.Property<string>("Phase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ReportsProcessed")
                        .HasColumnType("bigint");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScopeKey");

                    b.HasIndex("NextRetryAtUtc");

                    b.ToTable("RankedWarHistoryBackfillState", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.RankedWarHistoryEntity", b =>
                {
                    b.Property<long>("WarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactionChain")
                        .HasColumnType("integer");

                    b.Property<long>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("FactionScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OpponentChain")
                        .HasColumnType("integer");

                    b.Property<long>("OpponentFactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpponentFactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("OpponentScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReportCapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReportIngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("WinnerFactionId")
                        .HasColumnType("bigint");

                    b.HasKey("WarId");

                    b.HasIndex("EndedAtUtc");

                    b.HasIndex("FactionId", "StartedAtUtc");

                    b.HasIndex("OpponentFactionId", "StartedAtUtc");

                    b.ToTable("RankedWarHistory", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.RankedWarReportMemberEntity", b =>
                {
                    b.Property<long>("WarId")
                        .HasColumnType("bigint");

                    b.Property<long>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attacks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Chain")
                        .HasColumnType("integer");

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIdleAttacker")
                        .HasColumnType("boolean");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("StatusState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StatusUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WarId", "FactionId", "MemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("FactionId", "MemberId");

                    b.HasIndex("WarId", "FactionId");

                    b.ToTable("RankedWarReportMembers", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.StoredApiKeyEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("ConsentRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TornPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("AnonymousId");

                    b.HasIndex("ConsentRecordId");

                    b.HasIndex("ConsentRecordId", "AnonymousId");

                    b.ToTable("StoredApiKeys", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.UserLogEntryEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("text");

                    b.Property<double?>("DefenseBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("DefenseIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("DexterityBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("DexterityIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyUsed")
                        .HasColumnType("double precision");

                    b.Property<int?>("HappyBeforeApi")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyBeforeDelta")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyBeforeTrain")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyDecreased")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyIncreased")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyUsed")
                        .HasColumnType("integer");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHappyAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHappyBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<double?>("SpeedBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpeedIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("StrengthBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("StrengthIncreased")
                        .HasColumnType("double precision");

                    b.HasKey("AnonymousId", "LogEntryId");

                    b.HasIndex("AnonymousId", "LogTypeId");

                    b.HasIndex("AnonymousId", "OccurredAtUtc");

                    b.ToTable("UserLogEntries");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.WarCurrentEntity", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FactionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OpponentFactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpponentFactionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WarId")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeKey");

                    b.HasIndex("WarId")
                        .IsUnique()
                        .HasFilter("\"WarId\" IS NOT NULL");

                    b.ToTable("WarCurrent", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.WarPollerHeartbeatEntity", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("ActiveWarId")
                        .HasColumnType("bigint");

                    b.Property<int>("FailureBackoffSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PollCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PollStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StaleAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScopeKey");

                    b.HasIndex("ActiveWarId");

                    b.HasIndex("Phase", "UpdatedAtUtc");

                    b.ToTable("WarPollerHeartbeats", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.WarRosterSnapshotEntity", b =>
                {
                    b.Property<long>("WarId")
                        .HasColumnType("bigint");

                    b.Property<long>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attacks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Chain")
                        .HasColumnType("integer");

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("StatusState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StatusUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WarId", "FactionId", "MemberId");

                    b.HasIndex("WarId", "CapturedAtUtc");

                    b.ToTable("WarRosterSnapshots", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.WarScoreSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FactionChain")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FactionChainLapsesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FactionScore")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentChain")
                        .HasColumnType("integer");

                    b.Property<long>("OpponentFactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpponentFactionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OpponentScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SampledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WarId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WarId", "SampledAtUtc");

                    b.ToTable("WarScoreSamples", (string)null);
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.StoredApiKeyEntity", b =>
                {
                    b.HasOne("HappyGymStats.Data.Entities.ConsentRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("ConsentRecordId", "AnonymousId")
                        .HasPrincipalKey("Id", "AnonymousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyGymStats.Data.Entities.IdentityMapEntity", null)
                        .WithOne()
                        .HasForeignKey("HappyGymStats.Data.Entities.StoredApiKeyEntity", "AnonymousId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
