// <auto-generated />
using System;
using HappyGymStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyGymStats.Data.Migrations
{
    [DbContext(typeof(HappyGymStatsDbContext))]
    partial class HappyGymStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HappyGymStats.Data.Entities.AffiliationEventEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "SourceLogEntryId");

                    b.HasIndex("PlayerId", "Scope", "AffiliationId");

                    b.ToTable("AffiliationEvents");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.DerivedGymTrainEntity", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClampedToMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyAfterTrain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyBeforeTrain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HappyUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHappyAtTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegenHappyGained")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegenTicksApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("DerivedGymTrains", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.DerivedHappyEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClampedToMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Delta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HappyAfterEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyBeforeEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHappyAtTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLogId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SortOrder");

                    b.HasIndex("SourceLogId");

                    b.ToTable("DerivedHappyEvents", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportCheckpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLogTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunOutcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalAppendedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFetchedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ImportCheckpoints", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("LogsAppended")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LogsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("PlayerId", "StartedAtUtc");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.LogTypeEntity", b =>
                {
                    b.Property<int>("LogTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogTypeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LogTypeId");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ModifierProvenanceEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "LogEntryId", "Scope");

                    b.HasIndex("PlayerId", "VerificationStatus");

                    b.ToTable("ModifierProvenance");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.RawUserLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("RawUserLogs", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.UserLogEntryEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DefenseBefore")
                        .HasColumnType("REAL");

                    b.Property<double?>("DefenseIncreased")
                        .HasColumnType("REAL");

                    b.Property<double?>("DexterityBefore")
                        .HasColumnType("REAL");

                    b.Property<double?>("DexterityIncreased")
                        .HasColumnType("REAL");

                    b.Property<double?>("EnergyUsed")
                        .HasColumnType("REAL");

                    b.Property<int?>("HappyBeforeApi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyBeforeDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyBeforeTrain")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyDecreased")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyIncreased")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HappyUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHappyAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHappyBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpeedBefore")
                        .HasColumnType("REAL");

                    b.Property<double?>("SpeedIncreased")
                        .HasColumnType("REAL");

                    b.Property<double?>("StrengthBefore")
                        .HasColumnType("REAL");

                    b.Property<double?>("StrengthIncreased")
                        .HasColumnType("REAL");

                    b.HasKey("PlayerId", "LogEntryId");

                    b.HasIndex("PlayerId", "LogTypeId");

                    b.HasIndex("PlayerId", "OccurredAtUtc");

                    b.ToTable("UserLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
