// <auto-generated />
using System;
using HappyGymStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappyGymStats.Data.Migrations
{
    [DbContext(typeof(HappyGymStatsDbContext))]
    partial class HappyGymStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HappyGymStats.Data.Entities.AffiliationEventEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceLogEntryId")
                        .HasColumnType("text");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("EncryptedAffiliationId")
                        .HasColumnType("bytea");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionBefore")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("AnonymousId", "SourceLogEntryId");

                    b.HasIndex("AnonymousId", "Scope", "AffiliationId");

                    b.ToTable("AffiliationEvents");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.FactionIdMapEntity", b =>
                {
                    b.Property<int>("AffiliationId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactionAnonymousId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("AffiliationId");

                    b.HasIndex("FactionAnonymousId")
                        .IsUnique();

                    b.ToTable("FactionIdMap");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.FactionMembershipEntity", b =>
                {
                    b.Property<Guid>("FactionAnonymousId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberAnonymousId")
                        .HasColumnType("uuid");

                    b.HasKey("FactionAnonymousId", "MemberAnonymousId");

                    b.HasIndex("MemberAnonymousId");

                    b.ToTable("FactionMembership");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.IdentityMapEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedTornPlayerId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakSub")
                        .HasColumnType("text");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea");

                    b.HasKey("AnonymousId");

                    b.HasIndex("KeycloakSub")
                        .IsUnique()
                        .HasFilter("\"KeycloakSub\" IS NOT NULL");

                    b.ToTable("IdentityMap");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ImportRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("LogsAppended")
                        .HasColumnType("bigint");

                    b.Property<long>("LogsFetched")
                        .HasColumnType("bigint");

                    b.Property<string>("NextUrl")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("AnonymousId", "StartedAtUtc");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.LogTypeEntity", b =>
                {
                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LogTypeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogTypeId");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.ModifierProvenanceEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("AnonymousId", "LogEntryId", "Scope");

                    b.HasIndex("AnonymousId", "VerificationStatus");

                    b.ToTable("ModifierProvenance");
                });

            modelBuilder.Entity("HappyGymStats.Data.Entities.UserLogEntryEntity", b =>
                {
                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogEntryId")
                        .HasColumnType("text");

                    b.Property<double?>("DefenseBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("DefenseIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("DexterityBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("DexterityIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyUsed")
                        .HasColumnType("double precision");

                    b.Property<int?>("HappyBeforeApi")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyBeforeDelta")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyBeforeTrain")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyDecreased")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyIncreased")
                        .HasColumnType("integer");

                    b.Property<int?>("HappyUsed")
                        .HasColumnType("integer");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHappyAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHappyBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<double?>("SpeedBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpeedIncreased")
                        .HasColumnType("double precision");

                    b.Property<double?>("StrengthBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("StrengthIncreased")
                        .HasColumnType("double precision");

                    b.HasKey("AnonymousId", "LogEntryId");

                    b.HasIndex("AnonymousId", "LogTypeId");

                    b.HasIndex("AnonymousId", "OccurredAtUtc");

                    b.ToTable("UserLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
